# Generated by Django 5.2.5 on 2025-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='fio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='patronymic',
        ),
        migrations.AlterField(
            model_name='klass',
            name='name',
            field=models.CharField(max_length=2, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Учебный предмет'),
        ),
    ]
