# Generated by Django 5.2.5 on 2025-08-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_teacher_fio_remove_teacher_patronymic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=20, verbose_name='ФИО')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Onиcaниe')),
                ('price', models.TextField(blank=True, null=True, verbose_name='Цена')),
                ('author', models.ManyToManyField(to='myapp.klass', verbose_name='Класс')),
                ('subjects', models.ManyToManyField(to='myapp.subjects', verbose_name='Учебный предмет')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
