# Generated by Django 5.2.5 on 2025-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_teacher_is_hidden_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Активное'), ('hidden', 'Скрытое'), ('moderation', 'На модерации')], default='active', max_length=20),
        ),
    ]
