# Generated by Django 5.2.5 on 2025-10-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_hidden',
        ),
    ]
