# Generated by Django 5.2.5 on 2025-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_teacher_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Активное'), ('hidden', 'Скрытое'), ('moderation', 'На модерации'), ('rejected', 'Отклонённые')], default='moderation', max_length=20),
        ),
    ]
